### ISSUE TITLE
excludes parameter not working

### ISSUE THREAD

**Issue by timvink** [ignorantshr/mkdocs-add-number-plugin#8] opened 2020-03-09 19:39 UTC
I tried setting:

```yml
- mkdocs-add-number-plugin:
    excludes: 
        - TMD/
```

But all the files is the folder still have the heading numbers added. 

Did this functionality work for you?

I could submit another PR to fix it (after first finishing #4)

**Comment by ignorantshr** [comment] 2020-03-10 04:36
Yes, I have found the problem is to judge the way the documents are excluded is misleading. It is located in:
https://github.com/ignorantshr/mkdocs-add-number-plugin/blob/cfbd8e6f5892d86861a9d7cb3bd4e062d2f42803/mkdocs_add_number_plugin/plugin.py#L155
You can fix it.

**Comment by ignorantshr** [comment] 2020-04-15 06:06
Fixed in commit [b753966feb888468ecab6428bfb2d649e69999b3](https://github.com/ignorantshr/mkdocs-add-number-plugin/commit/b753966feb888468ecab6428bfb2d649e69999b3)

**Closed as completed by ignorantshr** 2020-04-15 06:06 UTC
Labels: bug
